#!/bin/bash
#
# Compile pint using GPC
#
# Note that GPC generates several unecessary warnings during
# the compile, including use of compiler directives in comments
# (in ISO 7185 mode it should just ignore them), and that it
# is generating 256 element sets by default (there does not
# seem to be any way to shut up this warning, including using the
# --setlimit option).
#

if [ ! -f pint.pas ]
then
   echo "*** Error: Missing pint.pas file"
   exit 1
fi

echo
echo Compiling pint.pas to create pint.exe
echo
gpc -o pint pint.pas --classic-pascal-level-0 --no-warnings --transparent-file-names --no-range-checking
