#!/bin/bash
#
# Compile pcom using GPC
#
# Note that GPC generates several unecessary warnings during
# the compile, including use of compiler directives in comments
# (in ISO 7185 mode it should just ignore them), and that it
# is generating 256 element sets by default (there does not
# seem to be any way to shut up this warning, including using the
# --setlimit option).
#

if [ ! -f pcom.pas ]
then
   echo "*** Error: Missing pcom.pas file"
   exit 1
fi

echo
echo Compiling pcom.pas to create pcom.exe
echo
gpc -o pcom pcom.pas --classic-pascal-level-0 --no-warnings --transparent-file-names --no-range-checking
